Refactor: use bulkWrite in updateJudge for improved efficiency
hackutd/jury pull request #216
Opened 2024-11-03 20:09 UTC by samrat-rm

### Description

refactor(updateJudge): replace individual updates with bulkWrite operation
- Switched to bulkWrite in updateJudge function to handle updates more efficiently.
- Reduces the number of database calls and improves performance.

### Fixes #[192]

### Type of Change 

Delete options that do not apply:

- Refactor (code changes that doesn't affect functionality)

### Is this a breaking change?

- [ ] Yes
- [x] No

2024-11-08 17:41 UTC, samrat-rm commented
@MichaelZhao21  Please review this PR for issue #192

2024-11-08 17:43 UTC, MichaelZhao21 commented
@samrat-rm commenting on a PR is not going to merge your PR faster.

2024-11-08 18:04 UTC, samrat-rm commented
> @samrat-rm commenting on a PR is not going to merge your PR faster.

Sorry, This is my first OS contribution and I am not sure what to do for my PR to get reviewed and merged.

2024-11-09 16:04 UTC, MichaelZhao21 requested changes

2024-11-09 16:04 UTC, MichaelZhao21 commented on server/database/judge.go
> +	_, err := db.Collection("judges").BulkWrite(context.Background(), models, opts)
Instead of using `context.Background`, you should use the provided `sc` mongo session context.

2024-11-12 15:59 UTC, MichaelZhao21 commented
@samrat-rm what is the status on the changes?

2024-11-12 19:50 UTC, samrat-rm commented
> @samrat-rm what is the status on the changes?

completed 👍  
Please review

2024-11-12 20:00 UTC, MichaelZhao21 approved these changes

2024-11-12 20:00 UTC, merged